name: ChunkProtect
author: goldmensch
main: de.goldmensch.chunkprotect.core.ChunkProtect
version: ${version}
api-version: 1.16

commands:
  chunkprotect:
    description: Main command of the ChunkProtect Plugin
    aliases:
      - chunk